# Generated by Django 2.1.3 on 2018-11-19 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0002_add_country_and_meta_class'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0001_add_lead_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the instance.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(editable=False, help_text='Timestamp when instance was created.')),
                ('updated_at', models.DateTimeField(editable=False, help_text='Timestamp when instance was last updated.')),
                ('email', models.EmailField(help_text='Email where we may reach customer.', max_length=254)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Prefix with +46 for Sweden and +47 for Norway.', max_length=128, null=True)),
                ('home_address', models.ForeignKey(blank=True, help_text='The home address of the customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Address')),
                ('leads', models.ManyToManyField(blank=True, help_text='Leads this customer has created.', to='leads.Lead', verbose_name='leads')),
                ('user', models.OneToOneField(blank=True, help_text='Connected user for the customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
