# Generated by Django 2.1.3 on 2018-11-19 22:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0002_add_country_and_meta_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the instance.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(editable=False, help_text='Timestamp when instance was created.')),
                ('updated_at', models.DateTimeField(editable=False, help_text='Timestamp when instance was last updated.')),
                ('email', models.EmailField(help_text='Email left by user, where an offer may be sent.', max_length=254)),
                ('uncleaned_address', models.CharField(help_text='Uncleaned input of the address that wants solar panels', max_length=64)),
                ('utm_campaign', models.CharField(help_text='Campaign, e.g. BlackFriday2018', max_length=64)),
                ('utm_medium', models.CharField(help_text='Advertising medium, e.g. email, Banner Ad or Pay per Click Ads', max_length=64)),
                ('utm_source', models.CharField(help_text='Channel, e.g. Google, Facebook', max_length=64)),
                ('address', models.ForeignKey(blank=True, help_text='Cleaned and verified address where user is interested in solar panels.', null=True, on_delete=django.db.models.deletion.PROTECT, to='location.Address')),
            ],
            options={
                'ordering': ('created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
