# Generated by Django 2.1.3 on 2018-11-19 22:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the instance.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(editable=False, help_text='Timestamp when instance was created.')),
                ('updated_at', models.DateTimeField(editable=False, help_text='Timestamp when instance was last updated.')),
                ('street_address', models.CharField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=13, max_digits=15, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=13, max_digits=16, null=True)),
            ],
            options={
                'ordering': ('created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the instance.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(editable=False, help_text='Timestamp when instance was created.')),
                ('updated_at', models.DateTimeField(editable=False, help_text='Timestamp when instance was last updated.')),
                ('code', models.CharField(help_text='National 2-digit identifier of County.', max_length=2, validators=[django.core.validators.RegexValidator(regex='^\\d{2}$')])),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the instance.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(editable=False, help_text='Timestamp when instance was created.')),
                ('updated_at', models.DateTimeField(editable=False, help_text='Timestamp when instance was last updated.')),
                ('name', models.CharField(max_length=50)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.County')),
            ],
            options={
                'ordering': ('created_at',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier of the instance.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(editable=False, help_text='Timestamp when instance was created.')),
                ('updated_at', models.DateTimeField(editable=False, help_text='Timestamp when instance was last updated.')),
                ('code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(regex='^\\d{4,5}$')])),
                ('name', models.CharField(help_text='Postal name of zip code', max_length=50)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.County')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Municipality')),
            ],
            options={
                'ordering': ('code',),
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.ZipCode'),
        ),
        migrations.AlterUniqueTogether(
            name='zipcode',
            unique_together={('code', 'county')},
        ),
    ]
