# Generated by Django 2.1.3 on 2018-11-19 22:58

import choicesenum.django.fields
from django.db import migrations
import graphy.location.enums


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_add_location_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'get_latest_by': 'created_at', 'ordering': ('created_at',), 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='county',
            options={'get_latest_by': 'created_at', 'ordering': ('name',), 'verbose_name_plural': 'Counties'},
        ),
        migrations.AlterModelOptions(
            name='municipality',
            options={'get_latest_by': 'created_at', 'ordering': ('name',), 'verbose_name_plural': 'Municipalities'},
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=choicesenum.django.fields.EnumCharField(default=graphy.location.enums.Country('no'), enum=graphy.location.enums.Country, max_length=2),
        ),
        migrations.AddField(
            model_name='county',
            name='country',
            field=choicesenum.django.fields.EnumCharField(default=graphy.location.enums.Country('no'), enum=graphy.location.enums.Country, max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('street_address', 'zip_code', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='county',
            unique_together={('name', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='municipality',
            unique_together={('name', 'county')},
        ),
    ]
